SOQL_Assignment/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassTeacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ClassTeacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student_Management/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Classes/src/classes/TestClassBeforeDelete.cls
/*
* Name : TestClassBeforeDelete
* Author : Anjita
* Created Date : 11/02/2016
* Usage : provide test coverage to class ClassBeforeDelete
*/
@isTest
public class TestClassBeforeDelete {

    /*
     * Setup method to initial data for test
     */ 
    @testSetup static void insertClass(){
        Contact teacher = new Contact(LastName = 'teacher1');
        insert teacher;
        Class__c class1=new Class__c(Name__c='1st' , ClassTeacher__c = teacher.Id);
        insert class1;
        Student__c student1= new Student__c(Last_Name__c='Student1',Class__c=class1.Id,Sex__c='Female');
        insert student1;
        Student__c student2= new Student__c(Last_Name__c='Student2',Class__c=class1.Id,Sex__c='Female');
        insert student2;
    }
    
    @isTest static void doNotDeleteClassWithFemaleStudents(){
        Class__c class1 = [SELECT Name__c FROM Class__c WHERE Name__c='1st'];
        test.startTest();
        Database.DeleteResult result = Database.delete(class1, false);
        Test.stopTest();
        system.debug(result);
        System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        System.assertEquals('Cannot delete Class, Class have more than one female students',
                            result.getErrors()[0].getMessage());
    } 
}