SOQL_Assignment/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassTeacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ClassTeacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Size__c</fullName>
        <label>Max Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>My_Count__c</fullName>
        <label>My Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Students__c</fullName>
        <label>No Of Students</label>
        <summaryForeignKey>Student__c.Class__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student_Management/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Classes/src/classes/TestStudentBeforeInsert.cls
/*
* Name : TestStudentBeforeInsert
* Author : Anjita
* Created Date : 11/02/2016
* Usage : provide test coverage to class StudentBeforeInsert
*/
@isTest
public class TestStudentBeforeInsert {

    /*
     * Setup method to initial data for test
     */ 
    @testSetup static void insertClass(){
        Contact teacher = new Contact(LastName = 'teacher1');
        insert teacher;
        Class__c class1=new Class__c(Name__c='Fourth',Max_Size__c=0,My_Count__c=0, ClassTeacher__c=teacher.id);
        insert class1;
    }
    
    @isTest static void donotAddStudentMoreThanMaxSize(){
        Class__c class1 = [SELECT Max_Size__c, No_Of_Students__c, My_Count__c FROM Class__c WHERE Name__c='Fourth'];
        System.debug(class1.No_Of_Students__c);
        Student__c student1= new Student__c(Last_Name__c='Stud',Class__c=class1.Id);
        Test.startTest();
        Database.SaveResult result=Database.insert(student1, false);
        Test.stopTest();
        System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        System.assertEquals('Can not insert student, Class has reached its maximum limit',
                            result.getErrors()[0].getMessage());
    }
}