SOQL_Assignment/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student_Management/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Web Service/src/classes/WebServiceContact.cls
/*
 * Name : WebServiceContact
 * Author : Anjita
 * Created Date : 15/02/2016
 * Usage : Web Service class functioning according to ........... 
 */ 
global class WebServiceContact {
	/*
	 * Passing the Query will Display the results Accordingly
	 */
    webservice static String queryForContact(String query) {
       
       // Gets the Query and Serialize the Result in the Form Of Query
       List<Contact> cntList = Database.query(query);
       String str = JSON.serialize(cntList);
       return str;
    } 
   
   /*
    *  Passing the Information will Create the Student in salesforce
	*/
    webservice static String createNewStudent(String name,String ClassId,String sex,Date dob) {
       
        // Setting the Value of the Student REcord
        Student__c std = new Student__c();
        std.Name = name;
        std.Class__c = ClassId;
        std.sex__c = sex;
        std.Date_Of_Birth__c = dob;
        insert std;
        return std.Id;
    }
}