Apex_Language_Assignment/src/objects/Class__c.object
<CustomObject>
    <description>Class having a number of students in it</description>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Apex_Language_Assignment/src/objects/Student__c.object
<CustomObject>
    <description>Student belongs to a particular class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>Class of the student.</description>
        <inlineHelpText>Select class of student.</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>First Name of student</description>
        <inlineHelpText>Fill First Name of student.</inlineHelpText>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last Name of student</description>
        <inlineHelpText>Fill Last Name of student.</inlineHelpText>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Apex_Language_Assignment/src/classes/ClassStudent.cls
public class ClassStudent {
    
   public static List<Student__c> getStudents(String classId){
       List<Student__c> studentList = [Select FirstName__c, Last_Name__c From Student__c Where Class__r.Id = :classId ];
       return studentList;
   }
   
    public static Map<Class__c,Set<ID>> getMapOfClass(){
        List<Class__c> classList=[select c.ID,c.Name from Class__c c];
        Map<Class__c,Set<ID>> map1=new Map<Class__c,Set<ID>>();
        for(Integer i=0; i<classList.size();i++){
         	Set<ID> studentSet= new Map<Id, Student__c>([Select s.ID from Student__c s where s.Class__r.id=:classList.get(i).Id ]).keySet();
        map1.put(classList.get(i),studentSet);
        }
        System.debug(map1);
     	return map1;
    }
    
   public static Integer workingDays(Date date1, Date date2){
     Integer NoOfDays = 0;
     Date tempStartDate = date1;
     for( integer i = 1; tempStartDate != date2; i ++ ) {
       if(tempStartDate.daysBetween(tempStartDate.toStartofWeek()) == 0 ||
                     tempStartDate.daysBetween(tempStartDate.toStartofWeek()) == -6)
       {
           tempStartDate = tempStartDate.adddays(1);
           continue;
       }
       NoOfDays = NoOfDays+1;
       tempStartDate = tempStartDate.adddays(1);
    }
     return NoOfDays ;
    }
}